# Generated by Django 6.0 on 2026-01-06 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatoTrafico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('velocidad', models.FloatField()),
                ('nivel_congestion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Nodes',
            fields=[
                ('id_nodo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('latitud', models.DecimalField(decimal_places=16, max_digits=22)),
                ('longitud', models.DecimalField(decimal_places=16, max_digits=22)),
            ],
        ),
        migrations.CreateModel(
            name='Arcs',
            fields=[
                ('id_arco', models.IntegerField(primary_key=True, serialize=False)),
                ('interseccion', models.IntegerField()),
                ('main_street', models.CharField(max_length=100)),
                ('sentido', models.CharField(max_length=100)),
                ('from_intersection', models.CharField(max_length=100)),
                ('to_intersection', models.CharField(max_length=100)),
                ('id_nodo1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arcos_origen', to='map.nodes')),
                ('id_nodo2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arcos_destino', to='map.nodes')),
            ],
        ),
    ]
