# Generated by Django 6.0 on 2026-01-26 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nodes',
            fields=[
                ('id_nodo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('interseccion', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Arcs',
            fields=[
                ('id_arco', models.IntegerField(primary_key=True, serialize=False)),
                ('interseccion', models.IntegerField()),
                ('calle_principal', models.CharField(max_length=100)),
                ('sentido', models.CharField(max_length=100)),
                ('desde_interseccion', models.CharField(max_length=100)),
                ('hasta_interseccion', models.CharField(max_length=100)),
                ('largo', models.IntegerField()),
                ('id_nodo1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arcos_origen', to='map.nodes')),
                ('id_nodo2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arcos_destino', to='map.nodes')),
            ],
        ),
        migrations.CreateModel(
            name='Traffic',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('calle_principal', models.CharField(max_length=100)),
                ('dia', models.CharField(max_length=100)),
                ('hora', models.TimeField()),
                ('plan', models.CharField(max_length=100)),
                ('tiempo', models.FloatField()),
                ('velocidad', models.FloatField()),
                ('tiempo_entre_largo', models.FloatField()),
                ('DCA', models.FloatField()),
                ('nivel_congestion', models.IntegerField(blank=True, null=True)),
                ('infeccion', models.IntegerField(blank=True, null=True)),
                ('id_arco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arco_hora_x', to='map.arcs')),
            ],
        ),
    ]
