# Generated by Django 6.0 on 2026-03-17 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traffic',
            name='nivel_promedio',
        ),
        migrations.RemoveField(
            model_name='traffic',
            name='promedio',
        ),
        migrations.CreateModel(
            name='Average',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('hora', models.TimeField()),
                ('dca_promedio', models.FloatField(blank=True, null=True)),
                ('nivel_promedio', models.IntegerField(blank=True, null=True)),
                ('id_arco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arco_promedio_x', to='map.arcs')),
            ],
        ),
    ]
