# Generated by Django 6.0 on 2026-01-16 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traffic',
            name='infeccion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
