# Generated by Django 6.0 on 2026-03-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_remove_traffic_nivel_promedio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='average',
            name='tiempo_entre_largo_promedio',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
