# Generated by Django 6.0 on 2026-01-12 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_traffic_id_alter_traffic_dia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traffic',
            old_name='n_intersección',
            new_name='n_interseccion',
        ),
    ]
